### ISSUE TITLE
Containers\Map.h(117): error C2665: “GetTypeHash”

### ISSUE THREAD

**Issue by usuiforhe** [hollsteinm/ReasonablePlanningAI#3]
I think the problem is 
	TMap<FAIRequestID, FAIMessageObserverHandle> MoveFinishedHandles;
	TMap<FAIRequestID, FAIMessageObserverHandle> RepathFailedHandles;

and I find these variables just use Add and Remove

**Comment by usuiforhe** [comment]
and My Unreal version is 5.2

**Comment by hollsteinm** [comment]
Thanks for the issue. I can look into it. Is this the latest version of Reasonable Planning AI?  I have yet to do a test build on 5.2.

**Comment by hollsteinm** [comment]
The fix for this is to add at the top of the RpaiActionTask_MoveTo.h file the following line before the class declaration:
```
/**
* GetTypeHash implementation for UE5.2.1 fix because it will not resolve for TMap
**/
FORCEINLINE uint32 GetTypeHash(const FAIRequestID& AIRequestID)
{
	return AIRequestID.GetID();
}
```

I will push a fix in the next few days after regression testing upgrades and updates for deprecation notices in Unreal Engine 5.2.1

Thank you for reporting the issue!

**Comment by hollsteinm** [comment]
Fixed by v0.0.5-5.2-alpha
